### ISSUE TITLE
Inject JS before running tasks

### ISSUE THREAD

**Issue by heysamtexas** [ben-eb/gulp-uncss#11]
I was wondering if there is a way to inject some javascript before running the uncss task. I'm uncss'ing a ReactJS app, and it needs the es5-shim.js file.

I'd rather not include it in my site, but rather just for phantomjs.

Is there a way we can inject arbitrary javascript using gulp-uncss?

I tested it directly using a sample javascript file and the onResourceReceived() method, and it works flawlessly:

```
var page = require('webpage').create();

page.onResourceReceived = function() {
    page.injectJs('js/es5-shim.min.js')
};

page.open('http://localhost:63342/expatel-frontend/index.html#/', function() {
    page.render('shot-1.png');
    phantom.exit();
});
```

I think it would be great to add this as an option, like so:

```
gulp.task('uncss', function() {
    return gulp.src(['file1.css','file2.css'])
        .pipe(uncss({
            html: [
                'http://localhost/index.html#/',
                'http://localhost/index.html#/other-path'
            ],
            inject: ['js/es5-shim.min.js']
        }))
        .pipe(gulp.dest('./out'));
});
```

**Comment by craft37** [comment]
complex selectors support really needed to use uncss.
