### ISSUE TITLE
Uncss disables twitter bootstrap navbar navigation

### ISSUE THREAD

**Issue by LoveAndHappiness** [ben-eb/gulp-uncss#24]
Hi there,

I don't know why, but using uncss just disables the dropdown menu of my navbar navigation. I explained the circumstances on stackoverflow (https://stackoverflow.com/questions/28082782/gulp-uncss-breaks-bootstrap-dropdown-navbar-navigation).

I understant that you aren't actually involved in the uncss part and that you just implemented exisitng technology for gulp, but I would like to know if you have any suggestion for this behaviour.

lovely regards,

your George

**Comment by ben-eb** [comment]
Duplicate of https://github.com/giakki/uncss/issues/64
