### ISSUE TITLE
ignored css not working

### ISSUE THREAD

**Issue by alanontheweb** [ben-eb/gulp-uncss#25]
Does the gulp plugin allow for this functionality? It doesn't seem to be doing anything for me.

/* uncss:ignore */
.selector1 {
    /* this rule will be ignored */
}

**Comment by ben-eb** [comment]
> Does the gulp plugin allow for this functionality?

Yes, it was added in `1.0.0`. Are you using the latest version?

**Comment by alanontheweb** [comment]
Yeah, I found the problem. Sass is exporting the comments in strange places. I'll have to play with it.Thanks!

**Comment by ben-eb** [comment]
:+1:
