### ISSUE TITLE
nmp install error? and global install stop for 24%

### ISSUE THREAD

**Issue by yyman001** [ben-eb/gulp-uncss#26]
C:\webapp>npm install --save-dev  gulp-uncss
\
> phantomjs@1.9.16 install C:\webapp\node_modules\gulp-uncss\node_modules\uncss\
node_modules\phridge\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\phantomjs\phantomjs-1.9.8-windows.z
ip
Receiving...

Error making request.
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "D:\\software\\nodejs\\\\node.exe" "D:\\software\\nodejs\\node_mod
ules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-uncss"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\webapp\npm-debug.log
help!

**Comment by ben-eb** [comment]
It looks like your network request is timing out. You might want to try a different mirror than bitbucket and try again. See the troubleshooting guide: https://github.com/Medium/phantomjs#troubleshooting

**Comment by ben-eb** [comment]
Closing as this is not an issue that can be resolved in this package's code.

**Comment by yyman001** [comment]
thanks~
