### ISSUE TITLE
Stripping JS-injected CSS

### ISSUE THREAD

**Issue by brettdewoody** [ben-eb/gulp-uncss#27]
I'm trying to use gulp-uncss with Zurb Foundation. Foundation has some JS to make dynamic elements the same height. It calculates the max-height of the matching elements, then injects an inline style to set the height of the elements. It does this when the page loads.

When I add gulp-uncss to my gulpfile.js the injected styles are no longer injected. Do you know why gulp-uncss would prevent this from happening?

**Comment by ben-eb** [comment]
Have a look at the `timeout` option - this allows for any JS execution to happen before the page is analysed.

**Comment by brettdewoody** [comment]
Thanks for the quick response :) 

I've tried setting a long timeout, 8000, and the issue is still present. Do you think this is an issue with UnCSS and I should open an issue over there?

**Comment by ben-eb** [comment]
Yup. This plugin just wraps the UnCSS module to allow it to consume files that are emitted by a vinyl stream. I think this is a potential duplicate of https://github.com/giakki/uncss/issues/139

Note that UnCSS does not process inline styles, only the CSS passed to it (in gulp-uncss' case, from the stream) or from `<link>` tags in the HTML.

**Comment by brettdewoody** [comment]
I just found that. I'll follow up on there. Thanks for the help.

**Comment by ben-eb** [comment]
No problem. :+1:
