### ISSUE TITLE
PHP Support

### ISSUE THREAD

**Issue by tonyspiro** [ben-eb/gulp-uncss#28]
Is there support for PHP?  I'm getting this error: 

gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };

Thanks!

**Comment by ben-eb** [comment]
Yes and no. You need to run UnCSS on HTML that would be outputted from a PHP script, not on raw PHP files; so, serve your application on a local server and run UnCSS on the relevant URLs.

```js
var gulp = require('gulp');
var uncss = require('gulp-uncss');

gulp.task('default', function() {
    return gulp.src('site.css')
        .pipe(uncss({
            html: ['http://localhost:3000/']
        }))
        .pipe(gulp.dest('./out'));
});
````

**Comment by tonyspiro** [comment]
Thanks Ben, I've found that replacing uncss with version 0.10.0 fixes it as well:

https://github.com/giakki/uncss/tree/0.10.0

**Comment by ben-eb** [comment]
Actually, I think this might be related to this issue: https://github.com/giakki/uncss/issues/150

My advice would be to stick with `0.10.0` until 150 is resolved upstream.

**Comment by AdletKoshanov** [comment]
THANK YOU
I did so: html: ['http://localhost/project/']
