### ISSUE TITLE
Using uncss on files with extension "blade.php"

### ISSUE THREAD

**Issue by pdoak** [ben-eb/gulp-uncss#30]
I am trying to use uncss on a laravel project where all the web files have an extension "blade.php" but I get errors if I use the following code:
`gulp.task('uncss', function() {
    gulp.src('build/css/myscss.min.css')
        .pipe(uncss({
                    html: ['index.blade.php','contact.blade.php']
                }))
        .pipe(gulp.dest('dest'));
});
`
If I change the "html" to files, I get the same error. What syntax do I need in order to get uncss to work with these file extensions.

Many thanks

Paul

**Comment by ben-eb** [comment]
UnCSS can't compile server side languages such as PHP. You'll need to serve your application on a local server and then get UnCSS to visit the relevant URLs. See https://github.com/ben-eb/gulp-uncss/issues/28
