### ISSUE TITLE
Leveraging PhantomJS settings, viewportSize, and others

### ISSUE THREAD

**Issue by obihill** [ben-eb/gulp-uncss#34]
Hi,

Great work on an awesome plugin! I used to use Chrome DevTools for this task but it's not very friendly when you need to output a clean CSS file. This works nicely. Kudos!

I was wondering if there was a way to leverage PhantomJS settings (e.g. userAgent) and viewportSize?

Thanks.

**Comment by ben-eb** [comment]
Not as far as I'm aware. All options are passed through to [UnCSS](https://github.com/giakki/uncss), it's probably worth opening an issue there for tracking this. If/when this lands it'll be automatically available in this module.
