### ISSUE TITLE
Ignore option is not working

### ISSUE THREAD

**Issue by mtwalsh** [ben-eb/gulp-uncss#37]
Hi,

Maybe I'm doing it wrong but I can't seem to get the ignore option working (v1.0.0 and v1.0.3), I'm using it as follows:

```
.pipe(uncss({
  ignore: ['.active'],
  html: [
    paths.serve + '**/*.html'
  ] 
}))
```

**Comment by ben-eb** [comment]
Try a regex. https://github.com/giakki/uncss/issues/161#issuecomment-91607682

```js
/\.active/
```

**Comment by mtwalsh** [comment]
Thanks, yes this is now working.

```
.pipe(uncss({
  ignore: [
    /\.active/
  ],
  html: [
    paths.serve + '**/*.html'
  ] 
}))
```
