### ISSUE TITLE
Uncss makes gulp-sourcemaps useless for me

### ISSUE THREAD

**Issue by 462960** [ben-eb/gulp-uncss#42]
That's how my gulp task looks like http://c2n.me/3sbh9c6.jpg
Source map gives far from correct result. I tried to place unss after destination of maps, where the blue arrow points.
Only disabling uncss lets perform correct sourcing.

Could you give me a hand, please?

**Comment by ben-eb** [comment]
UnCSS doesn't support sourcemaps.
