### ISSUE TITLE
how to scan css in javascript?

### ISSUE THREAD

**Issue by oliver0910** [ben-eb/gulp-uncss#43]
If i create a element and append to body, then use uncss to scan css file and html file.But the class named 'ccc' also will be cleared. Does uncss can support this situation?
Example code : 
var $aa = $("<div></div>");
$aa.addClass("ccc");
$('body').append($aa);

**Comment by ben-eb** [comment]
You can delay UnCSS evaluation until after your JS has loaded by using the `timeout` option. Note that it only supports JS injected at page load time, not classes added by user interaction. For this you should maintain an `ignore` list.

https://github.com/ben-eb/gulp-uncss#options
