### ISSUE TITLE
Confusion about globs as `html` files / URLs input

### ISSUE THREAD

**Issue by ifraixedes** [ben-eb/gulp-uncss#47]
I'm a bit confused about the description of the README related with the kind of values that `html` plugin property takes.

[Example section](https://github.com/ben-eb/gulp-uncss#example) mentions that the plugin accepts globs, however in the [options section](https://github.com/ben-eb/gulp-uncss#html) it doens't mention it.

If I'm not wrong, [the implementation doesn't make any processing of the property and it passes the value directly to uncss](https://github.com/ben-eb/gulp-uncss/blob/master/index.js#L27) and the documentation of uncss doesn't metion that globs may be use, although it includes [glob](https://github.com/isaacs/node-glob) as a dependency so it may be used for it, but I'm not user because I haven't inspected the uncss source code.

I found all of this when I couldn't get the result that I expected, setting as an `html` option value an array of two globs, for example:

```js
html: [ 'dist/**/*.html', '!dist/{amp,amp/**/*}']
```

Nonetheless it worked when I set it as string

```js
html: 'dist/**/*.html,!dist/{amp,amp/**/*}'
```

I think that uncss accepts globs however it doesn't combine them properly when they are set through different array elements.

This issues isn't about what uncss does or not, I'm going to open an issue there referencing this; this one is about the confusion that I had when I've read the README as I mentioned at the beginning.

**Comment by ifraixedes** [comment]
I found the issue [#51](https://github.com/giakki/uncss/issues/51) which mentioned how to use glob as input, so it seems that uncss doesn't accept glob and an external solution is fine than to implement it as a feature.

However it works on my example, so newer version accepts them.

**Comment by ifraixedes** [comment]
I was wrong; 

I don't get the error `PhantomJS: Cannot open about:blank` when I use the string value however, uncss remove styles which it shouldn't so, basically I think that uncss doesn't use globs.

**Comment by ben-eb** [comment]
> I think that uncss accepts globs however it doesn't combine them properly when they are set through different array elements.

That might be the case, yeah. This option was added later, after I had wrote the initial documentation, so I probably forgot to update it (although I did update the example). Any issues with that should probably be reported on the uncss tracker.

**Comment by ifraixedes** [comment]
@ben-eb ok thanks to confirm me that uncss added globs entries as a feature; with this I may take a look deeper to my usage and if I spot a strange behavior, then report it to uncss tracker

Let you know that I opened ([uncss/#215](https://github.com/giakki/uncss/issues/215)) an issue on it too, and pointed to this one to provide context, however, I closed because I wasn't totally sure if I was right after I found that I was wrong.
