### ISSUE TITLE
Just question.

### ISSUE THREAD

**Issue by chumack** [ben-eb/gulp-uncss#52]
Un css parse search classes in static html.

And what about if i add some elements by JS dynamically? You know what i mean?

**Comment by marioloncarek** [comment]
i could not find the solution for elements added by JS with UnCss, i moved to gulp-purifycss

**Comment by chumack** [comment]
I don`t believe that uncc have no any solution for this problem. But seems when i try check *.js, plugin don't see classes.
Please, developers, need feedback...

**Comment by ben-eb** [comment]
UnCSS doesn't support selectors added by user interaction, only those added on initial page load. To be honest you are best off exposing your classes added at runtime in your JS, to pass them to UnCSS' ignore option. How you do this really depends on your use case. :smile:

**Comment by bennyp123** [comment]
I moved the pipe to the html filter (after css was minified, etc) and got this

`missing '}' near line 1:2394
        1:     -> 54435c245.css"></head><body ng-class="{'`

can you add some logic to parse angular ngClass?

**Comment by ben-eb** [comment]
@bennyp123 You'll want to ask upstream. https://github.com/giakki/uncss/issues
