### ISSUE TITLE
Не работает /*! uncss:ignore */

### ISSUE THREAD

**Issue by Vadizar** [ben-eb/gulp-uncss#56]
Условие /*! uncss:ignore */ не работает в таком примере:

/*! uncss:ignore */
@keyframes warp {
    from {
        opacity: 0;
        transform: rotate(-60deg) translateZ(-300px)
    }
    to {
        opacity: 1;
        transform: rotate(60deg) translateZ(300px)
    }
}

**Comment by ai** [comment]
@Vadizar автор репозитория не знает русского — используй хотя бы Google Translate ;).

@ben-eb translation: “`/*! uncss:ignore */` doesn’t work in this example”

**Comment by ben-eb** [comment]
Could you please ask this in the UnCSS repository? This module just wraps that functionality so that it can fit into a gulp stream.

https://github.com/giakki/uncss/issues
