### ISSUE TITLE
Can't find uncss

### ISSUE THREAD

**Issue by funbunch** [ben-eb/gulp-uncss#57]
I've installed and uninstalled the plugin multiple times using:
    `npm install gulp-uncss --save-dev`

and and keep getting a cannot find module gulp-uncss error. I see it in my node folder and in the package.json. Any ideas?

**Comment by ben-eb** [comment]
Do you have any error logs?

**Comment by funbunch** [comment]
I do...here: 

![gulp-error](https://cloud.githubusercontent.com/assets/3441200/15482247/7b5dc2fa-20e3-11e6-87ff-a359ac2197bf.jpg)

**Comment by ben-eb** [comment]
Looks like you are requiring `gulp.uncss`, not `gulp-uncss`.

**Comment by funbunch** [comment]
:O Duh! I even noticed that in the error and didn't look back at my gulpfile or think enough of it. Thank you!

**Comment by ben-eb** [comment]
No problem. 😄
