### ISSUE TITLE
Look into JavaScript files and consider all strings as possible CSS classes 

### ISSUE THREAD

**Issue by mohsen1** [ben-eb/gulp-uncss#58]
The reason we're not using this plugin is that we've a bunch of JavaScript files that add CSS classes on the fly and those classes are used in CSS. This is a very common practice. 

My suggestion is to look into JavaScript files and consider all declared strings as possible classes. Maybe you should have a length limit. 

I'm aware of the fact that you can construct strings in JavaScript or use other means than classes (attributes or tag names) for styling. In our case we do not use attributes and tag names, we only and only use classes (atomic classes). We also don't combine or manipulate strings to construct CSS classes.

The option to look into JS code for possible should come with its caveats declared but it will be a very useful option for many.

**Comment by hinok** [comment]
@mohsen1 This is what exactly purifycss does https://github.com/purifycss/purifycss
We also use uncss in one of our projects but build time is a bit too long (5-6 minutes). Probably we will try and switch to purifycss which also parse js files.

**Comment by ben-eb** [comment]
Please can you direct feature requests to the UnCSS tracker, gulp-uncss is a very thin abstraction on top of it. Thanks! 👍
