### ISSUE TITLE
.php and .blade files

### ISSUE THREAD

**Issue by alirezaahmadi69** [ben-eb/gulp-uncss#59]
Your plugin is great but when i'm using it for .blade files it just fails. since many frameworks don't use simple .html files for views anymore it would be great if you add support for other files as well and kind of ignore non-html part of the page.

**Comment by ben-eb** [comment]
Please can you direct feature requests to the UnCSS tracker, gulp-uncss is a very thin abstraction on top of it. Thanks! 👍
