### ISSUE TITLE
Option html

### ISSUE THREAD

**Issue by ilkome** [ben-eb/gulp-uncss#61]
In docs says 

> html
>  Type: Array|String Required value.

But it's doesn't work with string.

**Comment by ilkome** [comment]
https://github.com/ilkome/front-end/blob/master/gulpfile.js/tasks/styles.js

Here in `css-clean` task if change `html: [paths.html.output],` to `html: paths.html.output,` - doesn't work.

**Comment by ben-eb** [comment]
The option works differently if you pass a string; it expects raw HTML content instead of a path.

> If you want to pass some HTML directly into the task instead, you can specify it here as a string.

**Comment by ilkome** [comment]
Thanks for explanation.
