### ISSUE TITLE
How to prevent delete @font-face definitions?

### ISSUE THREAD

**Issue by PixelT** [ben-eb/gulp-uncss#65]
I write:
```
.pipe(uncss({
    [...]
    ignore: [
        /@font-face/
    ]
}))
```
but they still delete the @font-face definitions....

**Comment by ben-eb** [comment]
Hi,

This isn't the right forum for this question, as I stated on the readme;

> If you have any difficulties with the output of this plugin, please use the [UnCSS tracker](https://github.com/giakki/uncss/issues).

This module is only a thin wrapper around UnCSS so any errors should be reported on their issue tracker.
