### ISSUE TITLE
Unknown word, unable to parse undefined

### ISSUE THREAD

**Issue by noeliablopez** [ben-eb/gulp-uncss#67]
Im trying to use gulp-uncss with all my js and css files. Only with the css files works fines, the problem is that my application.js has this structure:

```
"use strict";

(function () {})();
```

It seems that uncss doesn't recognize this line as js syntax and throw an error. How can I avoid this issue or only this line? Thank u!

This is the error I see on my console:

```
/Users/noeliabelenlopez/Documents/frontend-bootstrap/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/async.js:48
    fn = function () { throw arg; };
                       ^
CssSyntaxError: uncss/node_modules/css: unable to parse undefined:
<css input>:4:44: Unknown word
        1:        "use strict";
        2:
        3:        (function () {})();
        4:     -> sourceMappingURL=data:application/json;b
        5:
```

**Comment by ben-eb** [comment]
Hi,

This isn't the right forum for this question, as I stated on the readme;

> If you have any difficulties with the output of this plugin, please use the [UnCSS tracker](https://github.com/giakki/uncss/issues).

This module is only a thin wrapper around UnCSS so any errors should be reported on their issue tracker.
