### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by malcocerGit** [ben-eb/gulp-uncss#68]
I hope you can help me, this is my gulpfile

This is an array of my pages, is write in this mode because I use this in other task's :

```
var criticalPages = [{
    url : 'url1',
    name : 'index'
},
{
    url : 'url2',
    name : 'subpage'
}
];
```

My task is written in this way :

```
gulp.task('critical', function(){

    criticalPages.map(function(pages) {

        gulp.src(['./assets/output/css/main.min.css'])
        .pipe( uncss({ html : [ pages.url ] }) )
        .pipe( gulp.dest('../app/texts/'+ pages.name +'/' + pages.name + '.css') )

...
```

But I don't receive anything, even if I change the dest source.

**Comment by ben-eb** [comment]
Hi,

The paths should be retrievable from the local filesystem (relative to the gulpfile), or a URL. Please ensure that these files are on disk in the correct place. For example if you supply 'index' then the module will look for a file named 'index' in the same directory as the gulpfile.
