### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by Ferym26** [ben-eb/gulp-uncss#70]
Hi, i have a problem
[repo](https://github.com/Ferym26/CssClean)
Its simple task for clearning, but the output file (out/style.clean.css) has only comments from original style.css 
[trabl](http://joxi.ru/brRelWRuoV6RA1)

**Comment by ben-eb** [comment]
This module is only a thin wrapper of uncss, any problems with the output should be directed to their tracker. https://github.com/giakki/uncss/issues
