### ISSUE TITLE
Incomplete css

### ISSUE THREAD

**Issue by crisdany6** [ben-eb/gulp-uncss#71]
Hello, excuse my English

I need to remove unused css to the page: https://www.domain.de/.
Final output css no good, he must do its work without use   ignore : ['']

Screenshot after gulp-uncss to delete unused css 
http://h.dropcanvas.com/f2061/Screenshot%20from%202016-10-21%2010:43:57.png

What you can do?

Regards

**Comment by ben-eb** [comment]
Hi @crisdany6,

I'm not really sure that I understand your request. Using the `ignore` option is recommended, unless you have a website that doesn't use JS to manipulate any CSS classes. If you are using JS to add and remove classes and you have an incomplete CSS file after running UnCSS, you might want to revisit this option.

It's a bit late that I got to this issue so I can't see this screenshot any more (it's a 404 now), unfortunately.

Hope this helps!
