### ISSUE TITLE
fontconfig error

### ISSUE THREAD

**Issue by isiah-lloyd** [ben-eb/gulp-uncss#73]
The first time I ran uncss I got an error about fontconfig not being installed. It seems that it's a hidden dependency with phantomJS (see ariya/phantomjs/issues/10904). To fix this all I had to do was run:

`apt-get install fontconfig`

I don't know if this can be fixed in your code or if you could update the documentation to document this.

**Comment by ben-eb** [comment]
Hi @isiah-lloyd,

I think this is probably best asked in the main UnCSS repository; that way this is documented in a single location.

https://github.com/giakki/uncss
