### ISSUE TITLE
Disable PhantomJS

### ISSUE THREAD

**Issue by vojtanezdara** [ben-eb/gulp-uncss#74]
It's more like question than a issue, but don't know where to ask... Is it possible to disable PhantomJS? I generating output html file using PhantomJS before running uncss task (adding cookies to login) and when try to run uncss it fails because it tries to run javascript code on page without included libraries...

Any ideas?
Thanks a lot.

**Comment by ben-eb** [comment]
Hello @vojtanezdara,

I think PhantomJS is an essential part of the UnCSS module, it's used to analyse the HTML for selectors that are used. Perhaps you could run some script on the HTML before the UnCSS task and remove the linked `<script>` tags from it? That way, the JS won't be executed.

If you're still having issues it's best to ask in the main repo, this module is only a thin wrapper. 😄
