### ISSUE TITLE
Works with URLs, not local HTML files on Windows (10)

### ISSUE THREAD

**Issue by zerodburn** [ben-eb/gulp-uncss#76]
I'm pretty sure it's a Windows issue. If I use:

```
html: [ 
    'http://localhost:3000/index.html', 
    'http://localhost:3000/about.html',
    etc
]
```

uncss runs perfectly. If I try and use:

```
html: [ 
    './app/*.html'
]
```

There is no error, but the output CSS file only contains a html selector. I've tried `file:///c:/path/to/files/*.html` ` and every combination of relative path I can think of but I just can't get it to work. When I open an HTML file in a browser in Windows, the URL bar returns:

`file:///c:/path/to/files/*.html` but it seems like phantomjs doesn't like this.

**Comment by frenkieman** [comment]
I have exactly the same problem.
```
	.pipe(uncss({
		html:['app/index.html']
	}))
```
is not working

```
gulp.task('sass', function(){
  return gulp.src(input)
    .pipe(sass(sassOptions).on('error', sass.logError)) // Using gulp-sass
	.pipe(uncss({
		html:['http://localhost:3000/']
	}))
	.pipe(gulp.dest('app/css'))
	.pipe(browserSync.reload({
		stream:true
	}));
});
```
works

**Comment by SalomonSmeke** [comment]
👍 I am experiencing this on macOS, however.

**Comment by MathieuLoutre** [comment]
Same problem here, even the simplest HTML with a few classes only returns the `html` selector in the final CSS. OSX 10.11.6, Node 6.9.5.

**Comment by MaxMilton** [comment]
I've started running to this issue too on Linux.

**Comment by ben-eb** [comment]
I'm deprecating this module, please ask over at https://github.com/giakki/uncss/issues.
