### ISSUE TITLE
"TypeError: Bad argument" in a dependency?

### ISSUE THREAD

**Issue by callumflack** [ben-eb/gulp-uncss#77]
I've had this error in a project for 6 months. I've used the exact same gulpfile setup, with the same dependencies (from what I can tell!) in other projects and it _works_. I've tried updating all npm packages, deleting and reinstalling them all, then removing .SCSS imports one by one, then building it against target HTML files one by one. No dice.

Can anyone shed light on this error?

~

/Users/sticktoitiveness/REPOS/the-substation/node_modules/uncss/node_modules/bluebird/js/release/async.js:48
        fn = function () { throw arg; };
                           ^
TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:387:9)
    at /Users/sticktoitiveness/REPOS/the-substation/node_modules/phridge/lib/spawn.js:102:38
    at startPhantom (/Users/sticktoitiveness/REPOS/the-substation/node_modules/phridge/lib/spawn.js:72:20)

**Comment by NathanLovato** [comment]
Same issue here:
![image](https://cloud.githubusercontent.com/assets/12694995/22499889/98a04e6e-e861-11e6-8265-00ff39ffd00a.png)

It stopped working recently. Got the node 6.9.4 LTS version on Win10. Also tried updating, reinstalling node_modules, nothing helps.

**Comment by ben-eb** [comment]
Does this thread help? https://github.com/giakki/uncss/issues/75#issuecomment-202364587

**Comment by callumflack** [comment]
Thanks @ben-eb but no dice on that for me.

**Comment by NathanLovato** [comment]
Thanks, but same, doesn't help.

**Comment by NathanLovato** [comment]
A little update: The issue doesn't seem to come from gulp-uncss, but from uncss itself. I tried using the source module both with js and the command line interface, and I get the same error.

**Comment by ben-eb** [comment]
> The issue doesn't seem to come from gulp-uncss, but from uncss itself.

It's probably worth re-raising this on the UnCSS tracker in this case; https://github.com/ben-eb/gulp-uncss#readme.

**Comment by shgga2016** [comment]
how to solve this question?
