### ISSUE TITLE
SetProcessDpiAwareness failed: "COM error 0x80070005

### ISSUE THREAD

**Issue by jdfx** [ben-eb/gulp-uncss#78]
Please see [this issue from Zurb Foundation for Emails](https://github.com/zurb/foundation-emails/issues/704)

Un-commenting the use of the gulp-uncss plugin stops this error.

I am un-sure if this is a problem with gulp-uncss or Foundation. Opening an issue here perhaps you can help shed some light.

**Comment by ben-eb** [comment]
Hi @jdfx,

Looks to me like a problem with phantomjs: https://github.com/ariya/phantomjs/issues/14095

If you can re-raise this issue over at https://github.com/giakki/uncss/issues then the maintainers there will hopefully be able to help. This module is only a thin wrapper for use with gulp.
