### ISSUE TITLE
Example task doesn't work - fn = function () { throw arg; };

### ISSUE THREAD

**Issue by chrisj-skinner** [ben-eb/gulp-uncss#79]
I used the example task 

    `gulp.task('default', function () {
        return gulp.src('site.css')
            .pipe(uncss({
                html: ['index.html', 'posts/**/*.html', 'http://example.com']
            }))
            .pipe(gulp.dest('./out'));
    });`

I created a demo `site.css` file and have an `index.html` set up but
get the follow error in the console. `fn = function () { throw arg; };`

**Comment by ben-eb** [comment]
I'm deprecating this module, please ask over at https://github.com/giakki/uncss/issues.
