### ISSUE TITLE
Report on CSS Size/Selector Savings

### ISSUE THREAD

**Issue by talbs** [ben-eb/gulp-uncss#8]
Hi there! Thanks for the awesome Gulp plugin. 

After reading [this grunt-slanted article](http://addyosmani.com/blog/removing-unused-css/) about using UnCSS and getting the basic gulp-uncss features working in [my styles task](https://gist.github.com/10083655), I was wondering if there is an option to output the file size or selector savings from running UnCSS in a gulp notification or terminal message.

Is this something that exists either in UnCSS or gulp-uncss? If so, would you mind helping with some example syntax?

I'm just transitioning to use Gulp as part of my workflow, so this question may be just my ignorance showing. Thanks in advance for the help (and again for the sweet plugin).

**Comment by ben-eb** [comment]
Will add support if/when this lands, if it needs some extra functionality. But I'm closing for now as stale.
