### ISSUE TITLE
Nodeserver for uncss

### ISSUE THREAD

**Issue by lukasoppermann** [ben-eb/gulp-uncss#80]
Hey, I really like the idea of uncss and this packages is pretty neat!

so I know something was once mentioned in #19 but it has been quite a while. I think it is pretty common to create pages in the fly, for example when using a cms system. 

It would be extremely helpful and awesome if this package would spin up a server and crawl through all pages to check the css. 

Do you think something like this is possible?

**Comment by ben-eb** [comment]
Hi @lukasoppermann,

I think it's most likely out of scope for this project, but you could certainly use some crawler on your site to assemble a list of pages for UnCSS to run. You could certainly try something like https://github.com/missinglink/huntsman to do this - if you save the `res.uri` for each crawled page on your own site.

https://github.com/missinglink/huntsman/blob/master/examples/basic.js#L11

Then once you have the links assembled you can feed that into UnCSS. Hope this helps!
