### ISSUE TITLE
Create separate css files per globed html input

### ISSUE THREAD

**Issue by sprynm** [ben-eb/gulp-uncss#81]
I'm investigating if unique CSS could be generated then replace the <link> in the head of a set of pages.  I achieved this for a single file but would prefer spelling out the task for each page.  

Can gulp-uncss take HTML as a input then output a css file based on the file name? Alternatively, I could take the output and inject it directly with gulp-html-replace.

**Comment by ben-eb** [comment]
I'm deprecating this module, please ask over at https://github.com/giakki/uncss/issues.
