### ISSUE TITLE
Why are only html files supported?

### ISSUE THREAD

**Issue by SamThilmany** [ben-eb/gulp-uncss#82]
Many websites rely on php and a huge amount even uses Symfony or Laravel. Both of them use template files, so wouldn't it be great if ˋgulp-uncssˋ could also read ˋ.phpˋ, ˋ.html.twigˋ and other files?

**Comment by ben-eb** [comment]
Try using a crawler to get the HTML from your templates and you will be able to use UnCSS on that output. See https://github.com/ben-eb/gulp-uncss/issues/80#issuecomment-297408820.
